project:
  type: website
  output-dir: docs

website:
  title: "davinaaliu.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: taylorswift.qmd
        text: Taylor Swift TidyTuesday Analysis
      

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



