project:
  type: website
  output-dir: docs

website:
  title: "davinaaliu.github.io"
  navbar:
    right:
      - href: docs/index.html
        text: Home

      - href: docs/about.html
        text: About

      - text: Data Viz
        menu:
          - text: Taylor Swift TidyTuesday Analysis
            href: docs/taylorswift.html
      

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



