project:
  type: website
  output-dir: docs

website:
  title: "davinaaliu.github.io"
  navbar:
    left:
      - href: docs/index.html
        text: Home
      - docs/about.html
      - text: Data Viz
        menu:
        - text: Taylor Swift TidyTuesday Analysis
        - href: docs/taylorswift.html
      

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



