---
title: "Taylor Swift"
description: |
  Analysis of Taylor Swift data from TidyTuesday
author: Davina Liu
date: September 28, 2026
format:
  html:
    code-fold: true
    code-summary: "Show code"
    code-tools: true
---

```{r}
library(tidyverse)
```

```{r}
taylor_album_songs <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2023/2023-10-17/taylor_album_songs.csv')
taylor_all_songs <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2023/2023-10-17/taylor_all_songs.csv')
taylor_albums <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2023/2023-10-17/taylor_albums.csv')
```

```{r}
taylor_all_songs |>
    filter(!is.na(album_name), !is.na(duration_ms)) |>
    mutate(minutes = duration_ms / 60000) |>
    ggplot(aes(x = minutes, y = album_name)) +
    geom_boxplot() +
    labs(
    y = "Song length (minutes)",
    title = "Taylor Swift song length by album",
    caption = "Source: TidyTuesday 2023-10-17 (taylor R package)"
  )
```

